# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Boris Web App Development
email: boris@boriswebappdevelopment.ca
description: Boris Web App Development Blog
name: Boris Web App Development
baseurl: "/blog" # the subpath of your site, e.g. /blog
production_url : https://bmisljen.github.io/blog
url: "https://bmisljen.github.io" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: boris_webandapp
github_username:  bmisljen
disqus: boris-web-app-development
# Build settings
markdown: kramdown
theme: minima
permalink: /:year/:month/:day/:title/
plugins:
  - jekyll-feed

  # Includes an icon in the footer for each username you enter
footer-links:
  email: boris@boriswebappdevelopment.ca
  facebook:
  github: bmisljen
  instagram:
  linkedin:
  pinterest:
  rss: subscribe
  twitter: boris_webandapp
  stackoverflow: # your stackoverflow profile, e.g. "users/50476/bart-kiers"
  youtube: # channel/<your_long_string> or user/<user-name>
  googleplus: # anything in your profile username that comes after plus.google.com/
 
# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
exclude:
   - Gemfile
   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
